scr: SPECファイルの更新
メソッドの引数を追加したため反映させた。
まだエラーが残っているので解決する必要がある

issue: #53

  1) RGRB::Plugin::ServerConnectionReport::Generator#joined irc.cre.jp
     Failure/Error: subject { generator.joined('irc.cre.jp') }
     NoMethodError:
       undefined method `irc.cre.jp' for nil:NilClass
     # ./lib/rgrb/plugin/server_connection_report/generator.rb:36:in `joined'
     # ./spec/rgrb/plugin/server_connection_report/generator_spec.rb:11:in `block (4 levels) in <top (required)>'
     # ./spec/rgrb/plugin/server_connection_report/generator_spec.rb:12:in `block (4 levels) in <top (required)>'